name = "smartscore-backend"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[build]
command = "npm run build"

[vars]
JWT_SECRET = "your-secret-key-here"

# If you're using database bindings, uncomment and configure these
# [[d1_databases]]
# binding = "DB"
# database_name = "smartscore"
# database_id = "your-database-id"